# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57a05557c2083050447c43ee225c49c9b6ed08601a7dbebf4d9d6acde3a98c6100d40270bb9eda319b5eb41eebe4841a044d88e3c39c941b06f02080f56b36bb

test:
  secret_key_base: 1c5d8a332c1457518e8227d22bb6f470cb46040311b1564cd86292e9df40992cdf61f6fa3d87a2d3a7b62d32fad48744fa801a40fab8cc8fd92dacffa4af3520

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
